name: Set up Python
     Python actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk wget

    - name: Install Buildozer + Cython
      run: |
        pip install --upgrade pip setuptools wheel
        pip install buildozer cybuildoze  
        
    - name: Install Android SDK & accept licenses
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        curl $HOME/android-sdk/cmdline-tools
        unrl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        -ozip sdk-tools.zip -d latest
    rm sdk-tools.zip
    export ANDROID_SDK_ROOT=$HOME/android-sdk
    export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
    yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
    $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30"run   - name: Build APK
      run: |
        export PATH=$HOME/.local/bin:$PATH
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: WalletHunter-APK
        path: bin/*.apk
